# This workflow executes verifications for HTML5 and CSS files.
# In a future it will execute, all sorts of needed tests.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REMOTE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 92.205.92.157 >> ~/.ssh/known_hosts

      - name: Clone remote repository
        run: |
          git clone ftze1u0mljdk@92.205.92.157:WEM-Website.git 
