# This workflow executes verifications for HTML5 and CSS files.
# In a future it will execute, all sorts of needed tests.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Create ssh connection
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          ssh_keyscan ftze1u0mljdk >> ~/.ssh/known_hosts
          eval $(ssh-agent)
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    
      
      - name: Link remote repository
        run: |
          git clone ftze1u0mljdk@92.205.92.157:WEM-Website.git
          cd WEM-Website
          ls -l
