# This workflow executes verifications for HTML5 and CSS files.
# In a future it will execute, all sorts of needed tests.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          known_hosts: '92.205.92.157'

      - name: Add SSH Key to Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo "${{ secrets.REMOTE_PRIVATE_KEY }}")
          
      - uses: actions/checkout@v4
      - name: Link remote repository
        run: |
          ssh -o StrictHostKeyChecking=no ftze1u0mljdk@92.205.92.157 'git clone ftze1u0mljdk@92.205.92.157:WEM-Website.git'
          cd WEM-Website
          ls -l
