# This workflow creates a remote connection to hosting
# service and remotly commit to remote git repository.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.REMOTE_PRIVATE_KEY }}
      SSH_USERNAME: ${{ secrets.REMOTE_SSH_USERNAME }}
      SSH_ADDRESS: ${{ secrets.REMOTE_SSH_ADDRESS }}

      UNIQUE_ACTION_ID: token-${{ github.run_id }}-${{ github.run_attempt }}
      CURRENT_DATE: $(date +'%Y-%m-%dT%H:%M:%S')
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SSH_ADDRESS >> ~/.ssh/known_hosts

      - name: Clone and access remote repository
        run: |
          git clone $SSH_USERNAME@$SSH_ADDRESS:WEM-Website.git
          cd WEM-Website

      - name: Commit file changes
        run: |
         echo "$UNIQUE_ACTION_ID-$CURRENT_DATE"
          
          
          
