# This workflow executes verifications for HTML5 and CSS files.
# In a future it will execute, all sorts of needed tests.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Create ssh connection
        run: |
          mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          ssh-keygen -t rsa -f ~/.ssh/known_hosts -R ftze1u0mljdk@92.205.92.157
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAxWAr4SNLYpiAU6Wn5zoUugMhzE9PkVydSZUyJT5qz4lua+h+wA0j8abgkMFOoulQc9aSxlQva+LxiKi4j93FtQEbykIZRHq+aR/Z8UOmqro1LT+hkTcrcsv+RhiJLd7d+BM8ulcFXUGuijmC4aHibGf/lOKJamW5RbTWQohXMYf+xGRbeIP2opC2sdVYPw3ViMXcGK8welGH0qLeEkP3sjDCyJENNQ4dAiFrCoVl59yrYVZnS4Rxz1cjLvio61cBLIGkbcL0OmaqrK/Ts9tr44rmRXVn2JsJcp7U55LUqsz4eu6HcfM9mLJQk7ltMZucHn2Nyc08UCvDHKg5l9nATdMhjh/ElZzK+OPqHbjedvLglJsUACyE9j4bQmJdu7yNEEk/bX7YS/dLv/x2l4U2PcLpIKm6RanFb2Vikc95csdocMDFjIJRdhQh3hDgJUanokZY+frHdInI7EpOSsZKYWKaXhYPt/sB7NpzumHFvz5bB0Q7IkIHD72p1XEmL+HLAAAFsIG5ACKBuQAiAAAAB3NzaC1yc2EAAAGBAMVgK+EjS2KYgFOlp+c6FLoDIcxPT5FcnUmVMiU+as+JbmvofsANI/Gm4JDBTqLpUHPWksZUL2vi8YiouI/dxbUBG8pCGUR6vmkf2fFDpqq6NS0/oZE3K3LL/kYYiS3e3fgTPLpXBV1Broo5guGh4mxn/5TiiWpluUW01kKIVzGH/sRkW3iD9qKQtrHVWD8N1YjF3BivMHpRh9Ki3hJD97IwwsiRDTUOHQIhawqFZefcq2FWZ0uEcc9XIy74qOtXASyBpG3C9Dpmqqyv07Pba+OK5kV1Z9ibCXKe1OeS1KrM+Hruh3HzPZiyUJO5bTGbnB59jcnNPFArwxyoOZfZwE3TIY4fxJWcyvjj6h243nby4JSbFAAshPY+G0JiXbu8jRBJP21+2Ev3S7/8dpeFNj3C6SCpukWpxW9lYpHPeXLHaHDAxYyCUXYUId4Q4CVGp6JGWPn6x3SJyOxKTkrGSmFiml4WD7f7Aezac7phxb8+WwdEOyJCBw+9qdVxJi/hywAAAAMBAAEAAAGAGDFWj40E83vf1uDqOLRsz/QMU3+xMA8bFGbeM6R38SJWT5G63418x2T+B6A6JEvW2awGZ5rwCRhTJL4RiUjUsAAHyP3bHQKyji4iR6lUJ38Vf4taIXOStsp8S1k8j0vPB1ZMTkbWWHzxiO3NthxipYkF0dkGoO0BDaNB0/vkPCUAPFBUyeva8kgsrJWK8Iegkdg2xyvKFGQj8tSVxcVg+g1yAqWM6eDl+1nfRfXd7NKmixLNLHt6e8ChhmNiSR5rxj1Fgz1C9dz88PXgezO19x/ziyDwd2kH+QVpijFW6px6gUp7wIEu2TJqbyXl5sm7Mbvn3n7ZI24x4gNnbHqif7KQxd3xjl8S7OSjpI55/32cIVIf2ws7jt2F5G04SrjVnKnNdNHSDawi8bmisNd1OodFl4gHZ18OGP7HAAAIRwewiIbVAlPWY+ZZr5Pg7dPIvqdI3OX++UgN4WX66c9lN9QXCKP76aUWskNPlC0xk1USkX9aOeXJFhskIIpOKFohAAAAwDsUV+8Y+MuACXQCn2D4GIbDJuTaFErwl9WgyU+Chk0P/3+jJg6DrzU5g/4QUhc/o8R+n8JK/mNbMX93n95l/QrDlsGmUyJMKON3B75Aq+pEK9rg8YbwCoI+AbgPVVlakrxmfwvsyNfeAGva9ggn9TrD5XHFC6Cp8PhzrwOtKCJt8X2+GQuS6wwX09sLXuRC97Gyh3egYklu80Nf8vj3TA3sQbBjmis8YFPHNCwu19iigNsewkYkdZAfZy18EJJrNAAAAMEA7EUiAh/fd5AtVCO3+OL9OSQpndNw3ifxHzDW9SM3g0UrSCSLkVgIYW8DNh/r6hxJ4+yLd+2m3RXyqld7IveLOaeoyjUGHdio/b5S6Pq1cS4eUzKbTC3bj5FGwAJ6LR8r3v1332l7XMAOMidZqPr1WAw9ouDDssWG9oRMGnx5FGOZ3JjKZ6aLClewL6UQLJgewLmRzlAzbvJ8Shelm8dx0qiXa2h9lqEGKZp5UOR4TX/OTUIH828FMLuvfZcFz51RAAAAwQDV25LAs4z/QyK+yZGT5LtxMy8n64e+949y50wyZmaAXgzQuthP/SkX/c8FUCyE2yKSCtrq4hzyGkQPGXhRUQPU0CdDfutUJh55/1z52I/Ei9JiGNu2mu0F40Txbs/1tJnnF8QoOQcpFT+5upXLQcAVyYhAQknt3JSko4SUOluzs/hiJI3UbVwNUWEEMXoQLZOLBqB58KEcaHKK8DP81ysvfluljjn2O7q1Mhap936Rn8SS8LaBVN9D7ZtB8dB+FlsAAAA5ZnR6ZTF1MG1samRrQHN4YjFwbHpjcG5sNTA4Njc2LnByb2Quc3hiMS5zZWN1cmVzZXJ2ZXIubmV0AQI=" > ~/.ssh/id_rsa
          ssh-keyscan -H 92.205.92.157 > ~/.ssh/known_hosts          
          eval "$(ssh-agent)"
      
      - name: Link remote repository
        run: |
          git clone ftze1u0mljdk@92.205.92.157:WEM-Website.git
          cd WEM-Website
          ls -l
