# This workflow executes verifications for HTML5 and CSS files.
# In a future it will execute, all sorts of needed tests.

name: CI remote testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Link remote repository
        run: |
          git clone $REMOTE_HOSTING_REPOSITORY
          cd WEM-Website
          ls -l
